### ISSUE TITLE
Validacion campo Cliente o Categoria

### ISSUE THREAD

**Issue by xaviflores21** [DHM-DISTRIBUIDORA/.github#1]
Al momento de registrar pedido de un cliente, el campo cliente o categoria sea obligatorio para el vendedor.
para un mejor control de registro.

![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/db2099d9-e97f-4bd4-a754-f1c2bf96392c)

**Comment by Licethd** [comment]
Cliente sin categoría:
![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/72888760/36272178-a78a-456e-82cc-0b6027d676ea)

Mensaje a mostrar caso cliente sin categoría al dar clic en REALIZAR PEDIDO:
![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/72888760/4bca8146-e78e-4f25-bc22-2ec8f71d414c)

**Comment by xaviflores21** [comment]
Corregido!!
