### ISSUE TITLE
Permisos de registrar o levantar pedidos fuera de zona

### ISSUE THREAD

**Issue by xaviflores21** [DHM-DISTRIBUIDORA/.github#10]
Actualmente el vendedor puede levantar pedido desde cualquier lugar que se encuentre.

Si necesita levantar su pedido fuera de su zona asignada, un usuario administrador tiene que poder autorizar que ese vendedor pueda levantar dicho pedido donde se encuente, esto bajo la premisa que al iniciar su visita el cliente no se encuentre en su tienda.
Realiza una llamada a su promotor semanal y le pide el pedido.
Hay casos que estando en DHM sus clientes llaman y registran el pedido desde el lugar.

**Comment by rickypazd** [comment]
Corregido en la version 1.0.66,
Se agrego el rol Levantar pedidos fuera de zona si queremos que un vendedor pueda realizar un pedido a mas de 200 metros de distancia de un cliente le sale una alerta que no puede realizar pedidos fuera de zona.
Si le damos el rol al usuario ya no saldria la alerta.

<img width="639" alt="Screenshot 2024-02-28 at 23 34 06" src="https://github.com/DHM-DISTRIBUIDORA/.github/assets/35882906/31f80dc4-a271-4959-94ff-117dcbc112fc">

**Comment by xaviflores21** [comment]
funcionando correctamente.
