### ISSUE TITLE
Mapa App

### ISSUE THREAD

**Issue by xaviflores21** [DHM-DISTRIBUIDORA/.github#11]
Al navegar en mapa desde la App mapa/conductores no se puede ver los puntos marcados quienes estan activos o inactivos.
![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/83591be4-3dca-46d5-b2d5-9f59395244e3)

sin embargo, desde la web si se puede.
![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/082af76b-645b-47fb-b05f-02f44c1e34af)

**Comment by rickypazd** [comment]
Lo corregi en la version 1.0.66. 

![dummy](https://github.com/DHM-DISTRIBUIDORA/.github/assets/35882906/bf42a82c-e988-47ea-8296-ab34387a1505)

**Comment by xaviflores21** [comment]
buenisimo.
