### ISSUE TITLE
Reporte pedidos por vendedor se duplican

### ISSUE THREAD

**Issue by xaviflores21** [DHM-DISTRIBUIDORA/.github#13]
en un lapso de 9 a 10 am, todos los pedidos realizados empezaron a duplicarse.
JHON SOLIZ
![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/d84d83bc-6c75-48c8-8955-df897cbacc8a)

EDUARDO ARINEZ
![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/ea8d958c-7e7c-4f20-bff3-de54d436b7de)

ELYZETH BOHORQUEZ
![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/1ae34f12-6fa0-47bb-8998-d4d36beb0791)

por ahora, solo de esos tres.

**Comment by rickypazd** [comment]
Al parecer ya esta corregido por que hicimos una validacion con la hora y los segundos, como no pudimos replicar el caso queda pendiente de ver si vuelve a suceder.

**Comment by xaviflores21** [comment]
procedo a cerrar, en caso vuelve a aparecer. Se reabrira el issue.
