### ISSUE TITLE
Recorrido vendedor con clientes en la misma ubicacion

### ISSUE THREAD

**Issue by xaviflores21** [DHM-DISTRIBUIDORA/.github#14]
El vendedor alessandro levanto todos sus pedidos de manera normal, pero al finalizar y revisar su recorrido la ubicacion de sus clientes se registraron en la misma ubicacion.
Segun lo comentado por ricky, revisar los logs a nivel base de datos para saber el porque pasa eso. Posterior, realiazar su correccion.

ejemplos antiguos, ya fueron corregidos por el vendedor.

![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/e1b00aef-2306-40f2-b6bf-484a17295beb)
![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/702e44c6-540b-472e-b9fe-314b3c60de3d)

**Comment by ruddypazd** [comment]
Esto pasa porque se cuelga la ubicación issue  #15 #21

**Comment by xaviflores21** [comment]
procedo a cerrar el issue y hacer seguimiento a los issues #15 y #21
