### ISSUE TITLE
Rastreador falla cada cierto tiempo de horas activas

### ISSUE THREAD

**Issue by xaviflores21** [DHM-DISTRIBUIDORA/.github#15]
Buscar una solucion al problema del rastreador, se ha evidenciado hasta con mi persona que no permite registrar un pedido porque esta fuera de zona, sin embargo el cliente esta bien punteado y el vendedor se encuentra en el lugar punteado.

se tiene que desactivar el rastreador y volver a activar.
casos extremos se tiene que reiniciar el celular para que vuelva a funcionar nuevamente.

**Comment by ruddypazd** [comment]
Esto pasa porque se cuelga la ubicación issue  #21 #14

**Comment by xaviflores21** [comment]
el problema fue identificado, que es porque se cuelga.
ahora, busquemos una solucion para que no se cuelgue el rastreador y tener que hacer el proceso de reiniciar, borrar o desinstalar la App.

**Comment by rickypazd** [comment]
Ya se soluciono.

**Comment by xaviflores21** [comment]
se mantendra abierto por unos dias mas, para validar correctamente que no se vuelva a colgar.

**Comment by xaviflores21** [comment]
Validado!
