### ISSUE TITLE
Corregir Front End Reportes Dash Vendedores

### ISSUE THREAD

**Issue by xaviflores21** [DHM-DISTRIBUIDORA/.github#16]
No se visualizan los pedidos exitosos en Front End vendedores

![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/5fb6cd55-dc40-4944-91ba-f5bf7022f4a0)

**Comment by rickypazd** [comment]
Este bug esta relacionado con el issue #19 . Se corrigio en ese issue

**Comment by xaviflores21** [comment]
Sigue apareciendo el mismo problema.
no se ve sus ventas exitosas, todas las marcan como sin exito.

![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/9ec2471e-5f91-4fd9-99b4-98b279211787)

![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/1a296952-876e-491a-be6a-9762e662174c)

**Comment by xaviflores21** [comment]
procedo a cerrar este issue y estar pendiente del issue #19
