### ISSUE TITLE
Reportes Pendientes.

### ISSUE THREAD

**Issue by xaviflores21** [DHM-DISTRIBUIDORA/.github#17]
que reportes quedan pendientes por hacer?
por favor listar todos los reportes solicitados y senalar cuales fueron realizados, cuales estan en proceso y cuales quedan pendientes.

**Comment by rickypazd** [comment]
- [x] Reporte de ventas por vendedor

- [x] Reporte de entregas por conductor con mapa de su recorrido.

- [x] Poder ir al mapa del vendedor pinchando en su usuario desde los reportes.

- [x] Requerir la ubicacion al realizar un pedido o una visita.

- [x] Colocar anuncio de no se activo cuando veo el reccorrido de alguien q nunca se activo

- [x] Ver en mapa de un vendedor con colores las vicitas sus resultados y su reccorido. Si es posible ver cuando se activo y se desactivo.

- [x] Reporte por categoria de cuanto va a vendiendo un vendedor.

- [x] Ver cuantos vendedores y cuantos conductores estan activos y podes ver en lista quienes.

- [x] Resumen rapido de la actividad de un transportista y un vendedor. Example( Cuantos clientes asignados tiene, cuantos a visitado, cuantos an pedido, cuantos an rechazado, si esta activado o no esta activado )

- [ ] Mapa de calor que le pongas una linea y marque con color donde se vende mas. Filtro - Empresa, Producto,linea, vendedor.
- [ ]  Mostrar rechazos previos en el perfil del cliente 


- [x] Mover el mapa de usuarios a dentro de reporte por que no se encuentra escondido.

**Comment by xaviflores21** [comment]
Cuando se estima el inicio de los reportes faltantes?

**Comment by xaviflores21** [comment]
tenemos algun avance con estos reportes?

- [x] Reporte de ventas por vendedor
- [x] Requerir la ubicacion al realizar un pedido o una visita.
- [x] Colocar anuncio de no se activo cuando veo el reccorrido de alguien q nunca se activo
- [x] Reporte por categoria de cuanto va a vendiendo un vendedor.

- [x] Reporte de entregas por conductor con mapa de su recorrido.
- [x] Poder ir al mapa del vendedor pinchando en su usuario desde los reportes.
- [x] Ver en mapa de un vendedor con colores las vicitas sus resultados y su reccorido. Si es posible ver cuando se activo y se desactivo.
- [x] Ver cuantos vendedores y cuantos conductores estan activos y podes ver en lista quienes.
- [x] Resumen rapido de la actividad de un transportista y un vendedor. Example( Cuantos clientes asignados tiene, cuantos a visitado, cuantos an pedido, cuantos an rechazado, si esta activado o no esta activado )
- [ ] Mapa de calor que le pongas una linea y marque con color donde se vende mas. Filtro - Empresa, Producto,linea, vendedor.
- [ ]  Mostrar rechazos previos en el perfil del cliente 
- [x] Mover el mapa de usuarios a dentro de reporte por que no se encuentra escondido.

**Comment by rickypazd** [comment]
se solicita que aqui salga el importe. Analizar. 
![Screenshot 2024-03-20 at 17 00 55](https://github.com/DHM-DISTRIBUIDORA/.github/assets/35882906/c3fe810b-e6d8-4d1f-9f03-30bf128b07d9)

**Comment by rickypazd** [comment]
Agregar filtro por vendedor. 
![Screenshot 2024-03-20 at 17 01 39](https://github.com/DHM-DISTRIBUIDORA/.github/assets/35882906/2ca44da4-82ea-4800-a254-b1d19969eb87)

**Comment by rickypazd** [comment]
![Screenshot 2024-03-20 at 17 02 15](https://github.com/DHM-DISTRIBUIDORA/.github/assets/35882906/437fac1f-838a-4404-a6aa-8694bade9b18)
Filtro de vendedor.

**Comment by rickypazd** [comment]
se resolvieron las solicitudes solo queda pendiente 

 Mapa de calor que le pongas una linea y marque con color donde se vende mas. Filtro - Empresa, Producto,linea, vendedor.

 Mostrar rechazos previos en el perfil del cliente

**Comment by rickypazd** [comment]
Se va a cerrar este issue y se va a crear 1 individual por cada reporte faltante.

**Comment by xaviflores21** [comment]
validado!
