### ISSUE TITLE
Mostrar algun tipo de mensaje cuando se busca la ruta de un usuario

### ISSUE THREAD

**Issue by xaviflores21** [DHM-DISTRIBUIDORA/.github#18]
normalmente aparece de esta manera:
![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/b444909e-c42f-4a04-ad84-e3a07b2dad4b)

si el usuario no tiene activado su rastreador o esta inactivo mostrar una alerta o algo que especifique y de detalles.
solo sale que esta cargando y no sabemos el motivo exacto.

![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/c24a108c-9783-4ae6-9b2e-6b2bbdab6df7)

**Comment by Licethd** [comment]
sería de gran ayuda que las capturas desde la PC incluyan la ruta o link de la vista,  y las capturas del celular una guía de la ruta donde se está observando. Al inicio de cada issue decir si la observación es en ADMIN, VENDEDOR, TRANSPORTISTA

**Comment by xaviflores21** [comment]
Perfecto, dare mas detalles y corregire los issues que no se entienda.

**Comment by ruddypazd** [comment]
Porfavor mostrar la url para saber donde es el problema

**Comment by xaviflores21** [comment]
Esta bien el mensaje, pero no especifica el porque del problema.
Los supervisores necesitan saber porque no pueden ver la unicacion del vendedor o tranportista.
ademas, no hay manera de mantener la ventana para volver atras en vez que reinicie toda la App?

![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/8de0c835-35c6-4da1-81a6-d6ff6a7b5907)

al darle reportar o ignorar, reinicia la app y te lleva al inicio.

**Comment by xaviflores21** [comment]
seguimos sin saber el motivo del error.

https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/6c673c0a-a05e-477e-bfb9-8ed16d67cac5

**Comment by Licethd** [comment]
se corrigió!

**Comment by xaviflores21** [comment]
sigue el problema, se cierra este issue y se abre otro en especifico.
