### ISSUE TITLE
Pedidos levantados como no exitoso 

### ISSUE THREAD

**Issue by xaviflores21** [DHM-DISTRIBUIDORA/.github#19]
revisar en el front end los pedidos que salen como no visitados, sin embargo si se le levanto el pedido al cliente.

![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/b1abe8ed-5672-4967-a607-e863eed7caad)

![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/170cc2f1-efb1-4416-b7fa-12e11430a91e)

**Comment by rickypazd** [comment]
Pasa que se agregon el asento al la key 'REALIZO PEDIDO' cosa q no los encontraba, para solucionar se ejecutara esta consulta periodicamente hasta que todos los vendedores tengan la version  `1.0.57`

**Comment by rickypazd** [comment]
```sql
update public.visita_vendedor set tipo = 'REALIZO PEDIDO' where tipo = 'REALIZÓ PEDIDO';
```

**Comment by rickypazd** [comment]
Cerramos el #16  por que es el mismo caso que este.

**Comment by xaviflores21** [comment]
aun persiste el problema. 
pongo de ejemplo este vendedor, hasta este momento tiene 22 pedidos levantados y ninguno sin exito.
si se revisa en el mapa, tiene algunos en verdes, otros en naranja como que no fueron visitados.

![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/0ad1ef1f-5f56-4d0b-988b-d554bf6e8db8)

**Comment by xaviflores21** [comment]
por favor, dar prioridad a la correcion de los visitados.
todos estos pedidos fueron levantados de manera exitosa, pero sigue apareciendo en naranja como no visitados.

![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/0b252606-a511-4d09-afe6-925fe9bf8471)

**Comment by ruddypazd** [comment]
Para que funcione tiene que estar en la ultima version, hoy vamos a obligar

**Comment by xaviflores21** [comment]
cuando suben la siguiente actualizacion?

**Comment by ruddypazd** [comment]
Esperamos que para mañana este la ultima

**Comment by xaviflores21** [comment]
validado!
