### ISSUE TITLE
Validacion Tranportista para entregar pedido

### ISSUE THREAD

**Issue by xaviflores21** [DHM-DISTRIBUIDORA/.github#21]
Realizar la misma validacion de vendedores en tranportista, para que no entreguen los pedidos fuera de zona asignamada

![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/253453a9-786d-43eb-a555-3c4f8c436113)

**Comment by ruddypazd** [comment]
Esto pasa porque se cuelga la ubicación issue  #15 #14

**Comment by xaviflores21** [comment]
validado!
