### ISSUE TITLE
Tranportista Reporte / Dash Transportista muestra Ausente cuando tienen su rastreo activado

### ISSUE THREAD

**Issue by xaviflores21** [DHM-DISTRIBUIDORA/.github#23]
Revisar dash transportista, muestra a todos los transportistas en general que estan ausentes pero si buscamos desde conductores si estan activos.

![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/527a09ce-6f47-4bb1-b202-d8172324c4e1)

**Comment by ruddypazd** [comment]
Se realizó la verificacion correspondiente.

En ambos casos se ve su ultima conexion.

![Screenshot from 2024-03-19 22-48-52](https://github.com/DHM-DISTRIBUIDORA/.github/assets/7370358/2da3d82f-65c5-4123-931a-b91bca6d7c04)

![Screenshot from 2024-03-19 22-49-06](https://github.com/DHM-DISTRIBUIDORA/.github/assets/7370358/d7b6f0d4-341f-49df-b1d1-72b992c06f6b)

**Comment by rickypazd** [comment]
Lo volvimos a abrir en la reunion por que en la ultima version vimos que igual paso y se creo otro issue mas arriba.

**Comment by Licethd** [comment]
corregido

**Comment by xaviflores21** [comment]
validado!
