### ISSUE TITLE
Tranportista / Cliente / Detalle Pedido Quitar detalle y aumentar vendedor

### ISSUE THREAD

**Issue by xaviflores21** [DHM-DISTRIBUIDORA/.github#26]
cuando ingresan al mapa y le dan click a cualquier cliente, en la ventana detalle pedido quitar NIT, ID Cliente, ID Venta y aumentar nombre del vendedor. 
Esto con la finalidad de saber a que vendedor le pertenece o saber que vendedor levanto pedido a dicho cliente. Tambien servira para que el conductor sepa que su cliente no se encontraba en la tienda o ya no quizo su pedido. Asi sabra y procedera a informar de lo sucedido. 

![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/81a69f0b-06eb-47d4-baf9-f505338034cd)

**Comment by ruddypazd** [comment]
Se acomodo a pedido.

**Comment by xaviflores21** [comment]
validado!
