### ISSUE TITLE
Mostrar Informacion en Reporte Transportista

### ISSUE THREAD

**Issue by xaviflores21** [DHM-DISTRIBUIDORA/.github#27]
Ver la forma mas optima de visualizar los vendedores que estan asignados al tranportista para su entrega.
esto con la finalidad de saber que tranportista tiene asignado que vendedor, la cantidad de boletas y el total por vendedor.
la captura de abajo, solo es un ejemplo mio.

![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/e3632b08-8ae3-454f-9d43-164d7446d519)

**Comment by rickypazd** [comment]
![ezgif-4-c0ba45d08e](https://github.com/DHM-DISTRIBUIDORA/.github/assets/35882906/9ac093f6-93d1-4c44-be02-100d99ddb82d)

**Comment by xaviflores21** [comment]
validado!
