### ISSUE TITLE
Quitar la opcion registro en Login

### ISSUE THREAD

**Issue by xaviflores21** [DHM-DISTRIBUIDORA/.github#28]
En login, quitar o deshabilitar la opcion registro de usuarios.
se ha evidenciado que hay varios registros de usuarios no pertenecientes a DHM que se crean usuarios innecesarios.

![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/1cd5c198-9e5e-4d81-a230-ec77970a21b3)

**Comment by ruddypazd** [comment]
Comentado el icono

**Comment by xaviflores21** [comment]
en la web y en el celular sigue apareciendo la opcion de registro.

![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/51d3df06-3be2-49b6-805e-8cad71b57baf)

**Comment by xaviflores21** [comment]
validado!
