### ISSUE TITLE
Tranportista / Mapa - Detallar los visitados

### ISSUE THREAD

**Issue by xaviflores21** [DHM-DISTRIBUIDORA/.github#30]
En el mapa del tranportista, realizar lo mismo que en el mapa del vendedor. Es decir, marcar en rojo los no visitados, naranja los rebotados o tienda cerradas y verde los pedidos entregados.
Actualmente, estan todos en verde, da entender que todos fueron entregados.

![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/ca36d2f3-dd1a-486f-9e4e-5f4cd4af77b1)

**Comment by ruddypazd** [comment]
favor mostrar la url en la foto para saber donde estamos.

**Comment by xaviflores21** [comment]
es en la app tranportista / mapa.
no hay url, es una captura del celular.

**Comment by xaviflores21** [comment]
validado!
