### ISSUE TITLE
Seccion Traportista agregar opcion ver los pedidos por vendedor

### ISSUE THREAD

**Issue by xaviflores21** [DHM-DISTRIBUIDORA/.github#31]
En la seccion del tranportista, agregar una opcion mas donde detalla los pedidos levantados por vendedor.
suponiendo que el tranportista Javier tiene asignado la zona sur y en su asignacion tiene 3 vendedores. mostrar ese detalle; por ejemplo algo parecido a la captura siguiente / Reporte / pero solo de los vendedores asignados:

![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/70d20aa7-4c82-4c3e-ac4c-fd1699913a39)
![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/eae2933a-357e-4efc-a7f1-2093d1886626)

![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/10dfdc2e-f198-4679-b5a0-eb91da5fdbc5)

**Comment by ruddypazd** [comment]
Se agrego lo solicitado

![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/7370358/fedc766f-6bd4-4cd5-9e5d-23e782294e41)

**Comment by xaviflores21** [comment]
validado!
