### ISSUE TITLE
Crear cliente desde la Web

### ISSUE THREAD

**Issue by xaviflores21** [DHM-DISTRIBUIDORA/.github#32]
al momento de querer crear un cliente desde la web, no despliega las opciones tipo cliente o categoria.

![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/b267a705-7f5c-4302-9b21-9c5290e56a16)

**Comment by ruddypazd** [comment]
Cuando era solo administrador no te salian

**Comment by xaviflores21** [comment]
validado!
