### ISSUE TITLE
Roles y permisos usuarios con asignacion vendedor

### ISSUE THREAD

**Issue by xaviflores21** [DHM-DISTRIBUIDORA/.github#33]
los usuarios que tienen una asignacion de vendedor, por mas que se le coloque los permisos de administrador no le permite descargar todos los clientes. Un ejemplo, el usuario del Supervisor Jose Alfredo tiene privilegios de administrador pero el tambien hace ruta levantando pedidos.
Mientras no se le asigne rutas no podra ver los clientes, por mas que tenga rol de administrador.

![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/b9388857-ace0-40df-9861-a3666b0810b7)

En perfil del empleado / ver usuarios - tiene que haber una opcion de desligar a ese usuario; algo parecido a sin asignacion o un campo que sea vacio. Porque mientras tenga asignado un usuario no podra ver la lista de los clientes como administrador.

![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/2132ffec-ef51-402d-a303-db63fcdf3e41)

![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/59a8c5b0-4fac-4e08-9a15-9be2d1079b5b)

![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/743ffb43-f022-4699-a06f-9ea858cf130a)

**Comment by ruddypazd** [comment]
Si borras el id_vendedor o transportista queda como admin

![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/7370358/6b68bc2b-41cf-455a-9ede-18a22ffa9f61)

**Comment by xaviflores21** [comment]
solucion validada.
