### ISSUE TITLE
La ubicacion del cliente se mueve.

### ISSUE THREAD

**Issue by rickypazd** [DHM-DISTRIBUIDORA/.github#34]
Verificamos que la ubicacion que figura en el sistema DHM es diferente a la ultima ubicacion encontrada en el historico de ediciones del cliente de servisofts. 
Cliente verificado: https://dhm.servisofts.com/tbcli/profile?pk=35012

Ubicacion que deberia ser: -17.89671675320728,-63.29092355445027

'Para verificar tubimos que entrar al sistema de DHM por anyDesk y ver en la tabla directo por la base de datos.'

**Comment by rickypazd** [comment]
Se sospecha que el sistema antiguo de DHM esta cambiando las direccines de los clientes al momento de asignar una ruta.

**Comment by rickypazd** [comment]
Se solucionó en la reunion. con la ayuda del equipo de DHM. Se descubrió que al momento de registrar un pedido a dm_cabfac se utilizaba la ubicación donde el vendedor se encontraba al registrar. 
Entonces al momento de facturar el pedido el sistema DHM modifica las ubicaciones del cliente a las latLng que ingresamos al pedido.

**Comment by xaviflores21** [comment]
validado!
