### ISSUE TITLE
App Vendedores lento al momento de levantar pedidos

### ISSUE THREAD

**Issue by xaviflores21** [DHM-DISTRIBUIDORA/.github#35]
cuando el vendedor visita a sus clientes asignados, demora bastante en guardar el pedido.
con un tiempo aproximado de casi 1 minuto para ser exactos.

![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/e04cfb00-2e08-47fc-887e-a9c43e56c336)

**Comment by rickypazd** [comment]
Se soluciono ya no requerimos la ubicacion para realizar un pedido.

**Comment by xaviflores21** [comment]
validado!
