### ISSUE TITLE
App Vendedor - no actualiza ubicacion del cliente cuando le dan editar

### ISSUE THREAD

**Issue by xaviflores21** [DHM-DISTRIBUIDORA/.github#36]
segun reporte de la vendedora, la semana pasada paso por su zona y algunos de los clientes que segun ella actualizo siguen sin la modificacion.

![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/4418c26d-311b-4bdd-a0a3-ce59ef849cbc)

seria ideal, que se coloque un campo fecha de modificacion y que fue lo que edito para tener una certeza de si lo hizo o no.
consulte a 3 vendedores, dos de ellos me dicen que algunos clientes no acutalizo la ubicacion mientras que el otro no tuvo ningun inconveniente cuando le da actualizar.

**Comment by rickypazd** [comment]
Ya eso se soluciono en la reunion que tuvimos con el equido de DHM.

**Comment by xaviflores21** [comment]
validado!
