### ISSUE TITLE
El transportista si se movio a las 12 del medio dia y dice ausente en el dashboard. IGUAL QUE EL ISSUE 23

### ISSUE THREAD

**Issue by rickypazd** [DHM-DISTRIBUIDORA/.github#38]
![Screenshot 2024-03-20 at 16 49 08](https://github.com/DHM-DISTRIBUIDORA/.github/assets/35882906/7b4599bb-2f65-4606-b148-5a6c1697b231)
![Screenshot 2024-03-20 at 16 49 26](https://github.com/DHM-DISTRIBUIDORA/.github/assets/35882906/04dc5a04-a450-45eb-9977-18514d31bb0d)

**Comment by xaviflores21** [comment]
validado!
