### ISSUE TITLE
Cuando mostramos al transportista los puntos a entregar queremos diferenciar por vendedor.

### ISSUE THREAD

**Issue by rickypazd** [DHM-DISTRIBUIDORA/.github#39]
Sugirieron colocar colores o algo que note que unos pedidos son de un vendedor y otros de otro.

![Screenshot 2024-03-20 at 16 53 03](https://github.com/DHM-DISTRIBUIDORA/.github/assets/35882906/9930a90a-3bef-4586-8ddc-5fdaf5b3d006)

**Comment by Licethd** [comment]
hecho

**Comment by xaviflores21** [comment]
solucioando!
