### ISSUE TITLE
Datos incompletos, nombre del vendedor no aparece al momento de crear nuevos clientes.

### ISSUE THREAD

**Issue by xaviflores21** [DHM-DISTRIBUIDORA/.github#4]
Al momento de crear un nuevo cliente, no esta asignando al vendedor correspondiente.
la forma de pago la toma por defecto al credito y tiene que ser al contado.
Tipo de documento tiene que ser documento y no exportacion.

![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/6ed484f0-ddb6-4a35-9ec2-16965984f7ce)

![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/722d127d-ec0b-49d4-927f-e96f218e8d03)

![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/b07cf1ce-a1ca-4221-8b71-3413aad4da76)

**Comment by ruddypazd** [comment]
Se resolvió en la version 1.0.65

**Comment by xaviflores21** [comment]
Al momento de crear cliente nuevo, ya no figura el nombre del vendedor.
favor de validar.

![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/bc29cd26-a306-49c8-bf5b-a42feec3ecb4)

**Comment by xaviflores21** [comment]
cual es el estado de este issue?

**Comment by xaviflores21** [comment]
Sigue saliendo sin el nombre del vendedor en adminsys.
Es cuando crean un nuevo cliente que no le aparece.

![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/27056deb-c371-49f1-bdef-5e3c7c0495d1)

**Comment by ruddypazd** [comment]
Se realizó la prueba correspondiente, y todo está correcto

![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/7370358/8918391d-457f-4cfc-b598-2f25c2fa400e)

**Comment by xaviflores21** [comment]
me vuelve a informar fabiola que no aparece el nombre del vendedor cuando crean un cliente nuevo.
![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/24c50ea0-84a6-4b52-a543-ba827269b45b)

![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/c7a3a379-0877-4322-85ef-f4f724b3b375)

intenten ingresando con el usuario de algun vendedor.

**Comment by xaviflores21** [comment]
Fabiola vuelve a indicar que no aparece los nombres de los vendedores cuando crean un nuevo cliente.

la lista es la siguiente:
Cliente:
![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/c11f4d6f-aa59-4df3-9a0d-1eaaa91f4ebf)
Vendedor: Diego Quiroz

Cliente:
![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/eee2cc8d-7d41-48c7-a8b0-bcdd235bf061)
Vendedor: ingrid Taborga

Cliente:
![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/4af8a883-666a-4fb6-9089-38a490ce57cc)
Vendedor: Ivan Somoza

**Comment by Licethd** [comment]
Ricky dice que en las reuniones se quedó que se posterga esta issue hasta la próxima semana

**Comment by rickypazd** [comment]
En la reunion del 2 de abril verificamos con bismark que si funciona. Pero se tomo en cuenta que si un cliente ya fue creado antes de que el error se aya corregido es necesario Editarlo para que este normal.

**Comment by xaviflores21** [comment]
Validado!
