### ISSUE TITLE
Desde la app mobile no funciona el click en el marcador de mapa.

### ISSUE THREAD

**Issue by rickypazd** [DHM-DISTRIBUIDORA/.github#41]
![Screenshot 2024-03-25 at 15 42 16](https://github.com/DHM-DISTRIBUIDORA/.github/assets/35882906/1970c474-f2e1-4b19-a683-11e18d498f34)

**Comment by Licethd** [comment]
corregido en móvil

**Comment by xaviflores21** [comment]
validado!
