### ISSUE TITLE
Filtro entre en transportistas y vendedores.

### ISSUE THREAD

**Issue by rickypazd** [DHM-DISTRIBUIDORA/.github#42]
![Screenshot 2024-03-25 at 15 43 29](https://github.com/DHM-DISTRIBUIDORA/.github/assets/35882906/b04774f8-41ae-4fc2-b22c-4a7206e1a7fb)

**Comment by Licethd** [comment]
hecho

**Comment by xaviflores21** [comment]
no esta funcionando el filtro, sigue apareciendo ambos.
vendedor yesin aparece en transportista

![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/b601d078-619a-4f7c-a26a-a16388db9447)

**Comment by xaviflores21** [comment]
Validado!
