### ISSUE TITLE
Cuando un transportista marca una entrega no puede modificar el estado de su entrega.

### ISSUE THREAD

**Issue by rickypazd** [DHM-DISTRIBUIDORA/.github#43]
Cuando un transportista realiza una entrega y el comercio se encuentra cerrado. marca como cerrado pero si vuelve mas tarde no puede marcar de nuevo o modificar el resultado previo de la visita.

**Comment by Licethd** [comment]
hecho

**Comment by xaviflores21** [comment]
validado!
