### ISSUE TITLE
Opcion Ventas no Funciona

### ISSUE THREAD

**Issue by xaviflores21** [DHM-DISTRIBUIDORA/.github#45]
en el menu principal / Ventas al dar click no realizar ninguna accion.

![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/2c34b8bf-9a80-4fba-86d1-22a34d875f7d)

analizar si esta opcion es necesaria, SI NO, quitar o ocultar el boton para que no sea visualizado.

**Comment by ruddypazd** [comment]
Esa ventana no tiene ninguna funcionalidad.

Se quitó la ventana de sistema.

**Comment by xaviflores21** [comment]
validado!
