### ISSUE TITLE
Usuarios / Ver rutas con error

### ISSUE THREAD

**Issue by xaviflores21** [DHM-DISTRIBUIDORA/.github#48]
En la App mobile, seccion usuarios / ver rutas aparece el mensaje de error.
y en el navegador web queda cargando.

![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/21b6854b-d597-429c-b090-c6921e9ef4b9)

**Comment by rickypazd** [comment]
Estara corregido en la version 1.0.72

**Comment by xaviflores21** [comment]
validado!
