### ISSUE TITLE
Crear un ejecutable para gestionar los backups del sistema en el server DHM

### ISSUE THREAD

**Issue by rickypazd** [DHM-DISTRIBUIDORA/.github#49]

**Comment by ruddypazd** [comment]
Se creó una carpeta en el escritorio con dos accesos directos uno de reiniciar el server y otro para sacar backups...

Tener en cuenta que para realizar el backup el sistema debe estar abajo, por lo cual si ejecuta el ardchivo del escritorio, éste automaticamente detendra el servidor DHM realizará el backup y volverá a encender el servicio.

El backup se guarda con el nombre de la fecha actual en la direccion D:/BKSERVISOFTS/

**Comment by xaviflores21** [comment]
solucionado!
