### ISSUE TITLE
Colocar actualizacion requerida en la App.

### ISSUE THREAD

**Issue by xaviflores21** [DHM-DISTRIBUIDORA/.github#5]
cuando ingresen a la app o al momento de darle click en activar rastreador, que los mande directamente a la play store para que actualicen su App, varios siguen usando la v.63 cuando ya estamos en la v.64.

que no los deje registrar ventas si no tiene la ultima actualizacio.

**Comment by ruddypazd** [comment]
Se obliga a tener instalada la V1.0.64

**Comment by xaviflores21** [comment]
para la actualizacion v.67 no me pidio o no me aparecio el mensaje que tengo que actualizar, tuve que ir directamente a la play store.
por favor revisar. Lo dejare abierto unos dias mas hasta la siguiente actualizacion y volver a revisar.

**Comment by xaviflores21** [comment]
sigue sin pedir actualizacion o mostrar mensaje que existe una actualizacion disponible.

https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/a1024c80-e06f-4c73-8d36-5255e523b622

sugiero que al momento de mostrar el mensaje que hay una actualizacion disponible, y presionen el boton que los lleve directo a la play store.

**Comment by rickypazd** [comment]
Se coloco a la version 1.0.70. en la reunion del martes
