### ISSUE TITLE
Que salga el vendedor y el tipo de cliente en el perfil del cliente.

### ISSUE THREAD

**Issue by rickypazd** [DHM-DISTRIBUIDORA/.github#50]
![Screenshot 2024-04-02 at 16 09 50](https://github.com/DHM-DISTRIBUIDORA/.github/assets/35882906/5cbcccdd-524f-4818-abbd-ec79141e1e81)

**Comment by Licethd** [comment]
hecho!!

**Comment by xaviflores21** [comment]
sigue sin aparecer!
![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/aff4256d-9f9f-4dd7-8bf7-210c34fc2132)

**Comment by rickypazd** [comment]
![Screenshot 2024-04-09 at 15 20 00](https://github.com/DHM-DISTRIBUIDORA/.github/assets/35882906/e6fc9349-c7ba-46d7-83df-ed332bb2f98e)

**Comment by xaviflores21** [comment]
solucionado!
