### ISSUE TITLE
Hay que diferenciar los rebotes parciales y totales. (REPORTES DE PEDIDOS REBOTADOS POR VENDEDOR)

### ISSUE THREAD

**Issue by rickypazd** [DHM-DISTRIBUIDORA/.github#51]
![Screenshot 2024-04-02 at 16 14 07](https://github.com/DHM-DISTRIBUIDORA/.github/assets/35882906/23b7bd8f-c8cf-4621-a5f8-02b0a5459779)

**Comment by xaviflores21** [comment]
validado!
