### ISSUE TITLE
Reporte de transportistas aparece clientes sin ubicacion

### ISSUE THREAD

**Issue by xaviflores21** [DHM-DISTRIBUIDORA/.github#52]
En reporte vendedores, aparece clientes sin ubicacion.
Supuestamente, esto fue corregido por todos los vendedores y no deberia existir clientes sin ubicaciones.
mismo caso que el issue cerrado #16 

![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/678a8968-fe86-4abd-b2bd-5d6f615b2342)

**Comment by Licethd** [comment]
Revisando la base de datos se puede ver que SÍ HAY varios clientes que nunca fueron modificados por sus vendedores, por tal motivo siguen sin coordenadas

**Comment by xaviflores21** [comment]
Pero como es posible que haya clientes sin ubicacion, se supode que la app no deberia dejar levantar pedidos sin ubicacion.
algo esta mal con la app
por favor revisar a profundidad.

@rickypazd @Licethd

**Comment by xaviflores21** [comment]
bismark, me confirma que esos clientes sin ubicacion tienen pedidos.

**Comment by rickypazd** [comment]
Los vendedores si nunca vendieron los clientes se quedan sin ubicacion. pero en la reunion del 9 de abril hablamos que este error se esta dando en transportistas y no en vendedores. Lo vamos a revisar mas adelante en la reunion.

**Comment by rickypazd** [comment]
Nos dimos cuenta en la reunion que eso sucede cuando los administrados de DHM registran un pedido directo del sistema Adminsys y es un cliente nuevo. Por eso se da como resuelto el problema.

**Comment by xaviflores21** [comment]
validado!
