### ISSUE TITLE
App transportista se cierra al momento de seleccionar un cliente para la entrega de pedido

### ISSUE THREAD

**Issue by xaviflores21** [DHM-DISTRIBUIDORA/.github#56]
![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/2fd8b3d6-5e30-426b-828d-24907d9af6f8)

https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/1097b974-cb2e-4ac8-a7b6-fdc9ad9882c7

**Comment by rickypazd** [comment]
Probar al momento de desagrupar y tambien agrupados.
