### ISSUE TITLE
Cuando el transportista realiza vicitas y luego sincroniza se baja el numero de visitas.

### ISSUE THREAD

**Issue by rickypazd** [DHM-DISTRIBUIDORA/.github#58]
AL parecer hay un problema al momento de realizar el registro de la visita desde la Base de datos REALM de telefono al servidor. 

https://github.com/DHM-DISTRIBUIDORA/.github/assets/35882906/fc265fd1-78c3-4f30-87d7-324d207f5695

**Comment by rickypazd** [comment]
Tratar de tenerlo listo para el lunes es urgente.

**Comment by xaviflores21** [comment]
![WhatsApp Image 2024-06-12 at 11 45 15_f30f903e](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/0da9eb2c-8b9e-444e-be99-5453bd6d1747)

Nombre Vendedor: Carlos villaroel
Uv 248

**Comment by xaviflores21** [comment]
validado!
