### ISSUE TITLE
Pedidos levatados en Transportista lejos de ubicacion actual

### ISSUE THREAD

**Issue by xaviflores21** [DHM-DISTRIBUIDORA/.github#6]
La vendedora Ingrid Taborga edito el dia sabado la ubicacion de la tienda para el transportista wilson sobre la avenida 5to anillo de la moscu, pero al momento de la entrega por el transportista, la ubicacion figura hasta 4 cuadras de la ubicacion actual.

 Segun la vendedora, lo marcado en verde son las tiendas de los clientes a entregar, pero figuran cuadras atras.

![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/a41f65df-8acb-4a11-abfb-dd241675d5ec)

Su respaldo del dia sabado, pero necesito otra forma de verificacion para saber si hubo cambios en la ubicacion al momento de la edicion.

![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/fc0fc237-a201-401e-86b4-533109a12724)

**Comment by xaviflores21** [comment]
cual es el estado de este issue?
tenemos avances en transportistas?

**Comment by xaviflores21** [comment]
Para el transportista sigue tomando un cliente que el vendedor no levanto el pedido.
![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/719a0597-2643-4ced-93ce-f56d18fe8c5e)

normalmente el vendedor al momento de levantar un pedido selecciona el primer cliente que le aparace en la lista, pero para el transportista solo ve el segundo cliente con una ubicacion que no fue actualizada o incorrecta.

se tiene que tomar si o si al cliente que el vendedor levanto el pedido.

**Comment by ruddypazd** [comment]
Ocurria un problema en la ubicacion de nuevos clientes, corregido

**Comment by xaviflores21** [comment]
Se corroboro que no hay problema con la App Transportista, todo se debe a los datos duplicados y clientes que no fueron punteados de manera correcta.

Otro punto; celular cacheado que no guardaba la ubicacion correcta del cliente.
