### ISSUE TITLE
Ver Ruta vendedor Supervisor Paul Salas

### ISSUE THREAD

**Issue by xaviflores21** [DHM-DISTRIBUIDORA/.github#7]
al seleccionar la fecha 23 de febrero sale el siguiente error

![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/e9beb335-e0a7-4699-8d67-f168b9eca6b7)

por favor verificar y validar.
mostrar un mensaje que indique al usuario cual fue el erro y que no se reinicie la app.

**Comment by xaviflores21** [comment]
cual es el estado de este issue?

**Comment by ruddypazd** [comment]
Tenemos entendido que el docker fue mal reiniciado y por esto estaba causando problemas.

**Comment by xaviflores21** [comment]
perfecto.
esperemos no vuelva a pasasr.
