### ISSUE TITLE
Nota de entrega con productos que no fueron levantados.

### ISSUE THREAD

**Issue by xaviflores21** [DHM-DISTRIBUIDORA/.github#8]
al momento de imprimir la boleta, hay productos que no fueron levantados por el vendedor.

![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/99e99bc7-aac5-488a-8b89-7bcfce4cb5fc)

**Comment by xaviflores21** [comment]
cual es el estado de este issue?

**Comment by Licethd** [comment]
Con una anterior actualización se corrigió y se espera que el error no se repita, en caso contrario reportar para volver a revisar

**Comment by xaviflores21** [comment]
perfecto, procedo a cerrar el issue, si vuelve a persistir el problema se reabre.
