### ISSUE TITLE
Registrar Ubicacion del cliente cuando sea necesario o cuando el cliente no tenga ubicacion

### ISSUE THREAD

**Issue by xaviflores21** [DHM-DISTRIBUIDORA/.github#9]
Al momento de actualizar la ubicacion, y el vendedor se queda sin megas, al momento de volver a tener internet el sistema guarda la ubicacion actual del vendedor.

he visto muchos casos de vendedores que se quedan sin megas, llegan a la oficinas de DHM, se conectan al wifi y sus pedidos suben al adminsys. Al momento de revisar los pedidos levantados de ese vendedor resulta que sus pedidos fueron levantados en las oficinas de DHM.

**Comment by xaviflores21** [comment]
Volver obligatorio el campo regitrar ubicacion del cliente solo si, el cliente no cuenta con una ubicacion.
Si el cliente ya cuenta con una ubicacion, recien habilitar la opcion de editar en caso la tienda se traslado al frente, al lado, etc.
o en caso que el vendedor registro una cuadra mas adelante.

Este cliente, ya cuenta con una ubicacion.
![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/aa8ac488-1654-4665-9638-99623b3f22b5)

Realizas el pedido correspondiente al cliente
![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/3a6a2fdf-b1a6-4230-b4de-f85d166bf453)

y te obliga a volver a colocar la ubicacion
![image](https://github.com/DHM-DISTRIBUIDORA/.github/assets/17733377/6d1045b4-b2b5-4de3-9dd3-dc5551d74c4c)

Es aqui, en este punto que vendedor que realiza la visita termina modificando la ubicacion exacta del cliente.
por otro lado, si no se selecciona ninguna ubicacion el sistema lo hace automatico. Y ese es otro motivo del porque el pedido levantado aparece una o dos cuadras de la ubicacion real.

**Comment by ruddypazd** [comment]
Se resolvio el problema en los clientes nuevos

**Comment by xaviflores21** [comment]
funcionando!

**Comment by xaviflores21** [comment]
abriendo issue para su correccion, los clientes que cuentan con ubicacion que no le vuelva a aparecer la ventana emergente.
que el mismo vendedor de click cuando vea que la ubicacion no es la correcta o el cliente se encuentra sin ubicacion.

**Comment by Licethd** [comment]
se hizo las pruebas correspondientes y solo obliga a colocar ubicación cuando el cliente no tiene las coordenadas, estamos en la versión 1.0.68 en las pruebas, en tus capturas dice versión 1.0.65

**Comment by xaviflores21** [comment]
las primeras capturas, efectivamente son de la v.65 por que en ese entonces estabamos con esa version.
Voy a corroborar con los vendedores para volver a cerrar el issue.

**Comment by xaviflores21** [comment]
validado!
